

export interface Intent {
  id?: number;        // optional because it's auto-generated by the backend
  name: string;       // logical name of the intent
  keyword: string;    // word/phrase that triggers the intent
  response: string;   // predefined bot response
}

