

import { ChatSession } from '../chat-session/chat-session-module';
import { Intent } from '../intent/intent-module';

export interface ChatMessage {
  id?: number;                 // optional, generated by backend
  sender: string;              // "USER" or "BOT"
  messageContent: string;
  timestamp: string;           // ISO string (maps to LocalDateTime)
  createdAt?: string;          // creation timestamp
  updatedAt?: string;          // last update timestamp
  chatSession?: ChatSession;   // optional to avoid circular reference
  intent?: Intent;             // optional, linked intent
}

